name: simple_quran_apps
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  data_connection_checker: ^0.3.4
  get: ^3.25.4
  google_fonts: ^1.1.2
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^0.3.0

flutter_native_splash:
  color: "#42a5f5"
  andoird: true
  image: assets/images/quran_icon.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/onboard_image.png
    - assets/images/quran_icon.png
    - assets/images/bismillah.png
